# Delay
# Delay further execution of a workflow by a fixed time
jobs:
- job: FunctionTrigger
  pool: Server
  steps:
  - task: AzureFunction@1
    inputs:
      function: https://covidtrackergenerator.azurewebsites.net/api/SiteGeneratorHttpTrigger
      key: '$(functionkey)'
      method: 'GET'
# this is being defined in app-ci pipeline
  resources:
    pipelines:
    - pipeline: Function-CI
      source: Function-CI
      trigger: 
        branches:
          include: 
              - main
