trigger: none
resources:
  pipelines:
  - pipeline: Function-CI
    source: Function-CI
    trigger: 
      branches:
      - main

jobs:
- job: FunctionTrigger
  pool: Server
  steps:
  - task: AzureFunction@1
    inputs:
      function: https://covidtrackergenerator.azurewebsites.net/api/SiteGeneratorHttpTrigger
      key: '$(functionkey)'
      method: 'GET'
